# 13장 연습문제

In [1]:
import numpy as np

## 1. 3줄 이내로 아래 배열을 생성하라

### 1-1번 배열
```
[[1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 2],
 [1, 6, 1, 1]]
```

In [2]:
arr_1_1 = np.ones((4, 4))
arr_1_1[3][1] = 6
arr_1_1[2][3] = 2

print(arr_1_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 2.]
 [1. 6. 1. 1.]]


### 1-2번 배열
```
[[0, 0, 0, 0, 0, 0],
 [2, 0, 0, 0, 0, 0],
 [0, 3, 0, 0, 0, 0],
 [0, 0, 4, 0, 0, 0],
 [0, 0, 0, 5, 0, 0],
 [0, 0, 0, 0, 6, 0]]
```

In [3]:
arr_1_2 = np.diag([2, 3, 4, 5, 6], k = -1)

print(arr_1_2)

[[0 0 0 0 0 0]
 [2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 6 0]]


### 1-3번 배열
```
[[4, 3, 4, 3, 4, 3],
 [2, 1, 2, 1, 2, 1],
 [4, 3, 4, 3, 4, 3],
 [2, 1, 2, 1, 2, 1]]
```

In [4]:
arr_1_3 = np.tile(np.arange(4, 0, -1).reshape((2,2)), (2, 3))

print(arr_1_3)

[[4 3 4 3 4 3]
 [2 1 2 1 2 1]
 [4 3 4 3 4 3]
 [2 1 2 1 2 1]]
