# NumPy 모듈

## NumPy 리스트

In [1]:
import numpy as np

a=np.array([0,1,2,3])
print(a)
print(type(a))

[0 1 2 3]
<class 'numpy.ndarray'>


In [2]:
b=np.array((0,1,2,3))
print(b)
print(type(b))

[0 1 2 3]
<class 'numpy.ndarray'>


In [3]:
c = a == b
print(c)

[ True  True  True  True]


In [4]:
d=np.array([True, True, False],dtype=int)
print(d)

[1 1 0]


### NumPy는 일반 리스트보다 빠르다

In [5]:
import time
start1=time.clock()
li_a=range(0, 100000, 2)
li_a_square=[i**2 for i in li_a]
end1=time.clock()
print("시간 1은", end1 - start1)

시간 1은 0.02349200000000007
/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """


In [6]:
start2=time.clock()
np_array=np.array(0, 100000, 2)
np_array_square**2
end2=time.clock()
print("시간 2은", end2 - start2)

/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


ValueError: only 2 non-keyword arguments accepted

### NumPy 리스트의 차원

In [7]:
li_1dim=np.array([0,1,2,3])
print(li_1dim)
print(li_1dim.ndim)

[0 1 2 3]
1


In [10]:
li_2dim=np.array([[1,2],[3,4],[5,6]])
print(li_2dim)
print(li_2dim.ndim)
print(li_2dim.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [ ]:
# np.array.shape == (len(np.array), np.array.ndim)