# NumPy 모듈

## NumPy 리스트

In [1]:
import numpy as np

arr=np.array([0,1,2,3])
print(arr)
print(type(arr))

[0 1 2 3]
<class 'numpy.ndarray'>


In [2]:
arr_2=np.array((0,1,2,3))
print(arr_2)
print(type(arr_2))

[0 1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(arr==arr_2)

[ True  True  True  True]


In [4]:
print(np.array([True, True, False],dtype=int))

[1 1 0]


### NumPy는 일반 리스트보다 빠르다

In [5]:
import time
start1=time.clock()
li_a=range(0, 100000, 2)
li_a_square=[i**2 for i in li_a]
end1=time.clock()
print("시간 1은", end1 - start1)

시간 1은 0.012197000000000013
/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """


In [6]:
start2=time.clock()
np_array=np.arange(0, 100000, 2)
np_array**2
end2=time.clock()
print("시간 2은", end2 - start2)

시간 2은 0.0010029999999999761
/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.
/home/kmlee/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  after removing the cwd from sys.path.


### NumPy 리스트의 차원

In [7]:
li_1dim=np.array([0,1,2,3])
print(li_1dim)
print(li_1dim.ndim)

[0 1 2 3]
1


In [8]:
li_2dim=np.array([[1,2],[3,4],[5,6]])
print(li_2dim)
print(li_2dim.ndim)
print(li_2dim.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [9]:
# np.array.shape == (len(np.array), np.array.ndim)

## NumPy 배열 자동 생성

#### np.arange

In [10]:
print(np.arange(1,11,2))

[1 3 5 7 9]


#### linspace

In [11]:
print(np.linspace(0, 1, 6, endpoint=False))

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333]


In [12]:

print(np.linspace(0, 1, 7))

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


#### zeros, ones
배열의 모든 값이 0또는 1인 배열을 만드는 함수

```
zeros((행,열))

In [13]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [14]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


#### np.diag
대각행렬을 만들거나 대각원소를 구하는 함수
```
diag([대각원소들])
diag([2차원 행렬], k=(주대각성분에서의 거리))
```

In [15]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [16]:
print(np.diag([[1,2,3],[4,5,6],[7,8,9]]))

[1 5 9]


#### eye
단위행렬을 만드는 함수
```
eye(행렬의 크기)
```

In [17]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 행렬 원소의 타입 확인 .dtype

In [18]:
print(np.ones((2,2)).dtype)
print(np.eye(3).dtype)

float64
float64


복소수를 만들 수 있다.

In [19]:
print(np.array([1+3j, 2+5j]).dtype)

complex128


### 난수 행렬

In [20]:
print(np.random.rand(5)) # 0에서 1 사이의 무작위 실수

print(np.random.randn(5)) # 정규분포

[0.91765585 0.97868246 0.54304465 0.67670292 0.55221486]
[-0.16835203  1.53579342  0.74481846  1.38278938 -0.99399192]
